name: Check Inclusive Language
on: [issues, pull_request]
jobs:
  check-language:
    runs-on: ubuntu-latest
    steps:
      - name: check-language
        uses: benhayehudi/inclusive-language-github-action@master
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
